#!/bin/sh

readonly CALCURSE_LOAD_DATA="${XDG_DATA_HOME:-$HOME/.local/share}/calcurse_load"

# create directory if it doesnt exist
[[ ! -d "$CALCURSE_LOAD_DATA" ]] && mkdir -vp "$CALCURSE_LOAD_DATA"

# gcal pre-load hook reads any json files in ~/.local/share/calcurse_load/
python3 -m gcal_index --email "myname@gmail.com" --credential-file "${HOME}/.credentials/<your_email>.json" >"${CALCURSE_LOAD_DATA}/calendar.json"
