#!/bin/bash

readonly CALCURSE_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/calcurse"

# for each .enabled extension file, run postsave
while read -r -d $'\0' ext; do
  "$ext" postsave
done < <(find "$CALCURSE_CONFIG" -type f -name "*.enabled" -print0)
