#!/usr/bin/env bash

THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
cd "${THIS_DIR}" || exit $?

# for each .enabled extension file, run postsave
find . -type f -name "*.enabled" -exec {} postsave \;
